### ISSUE TITLE
bitcoincash:qqne60dvls59j2ymt53leu4zc5y43m82mvx52l8qf0

### ISSUE THREAD

**Issue by Massipur** [Bitcoin-com/paperwallet.bitcoin.com#12]
bitcoincash:qqne60dvls59j2ymt53leu4zc5y43m82mvx52l8qf0

**Comment by Massipur** [comment]
bitcoincash:qqne60dvls59j2ymt53leu4zc5y43m82mvx52l8qf0

**Comment by josephroyking** [comment]
Spam

**Comment by Massipur** [comment]
No

**Comment by Massipur** [comment]
What is github?

I no think git gub (cara kerja)

Pada tanggal Sel, 19 Feb 2019 20:56 Joey <notifications@github.com menulis:
